- name: Get ChatGPT completion
  id: chatgpt
  uses: cahaseler/openai-chatgpt-action@v1
  with:
    apiKey: ${{ secrets.OPENAI_API_KEY }}
    prompt: 'Please generate github best practices formatted pull request content in markdown based on the following commit messages and diffs'
    input: 'put whatever you want in here'
    model: 'gpt-4'
    temperature: 1
    max_tokens: 200
              - name: chatgpt-action
                uses: unsafecoerce/chatgpt-action@release/v2
            
